name: Deploy to Web

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: NextJS Cache
        id: build-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install NPM Dependencies
        run: npm ci

      - name: NPM Tests
        run: NODE_ENV=test npm run test:ci

      - name: NPM Build
        run: npm run build

      - name: Build Image
        run: |
          docker build -t dev.dowell/flashchords .

      - name: Tag Image
        run: |
          docker tag dev.dowell/flashchords registry.digitalocean.com/dowell/flashchords:latest

      - name: Logs in to Digital Ocean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_REGISTRY_KEY }}

      - name: Push to Registry and Collect Garbage
        run: |
          doctl registry login --expiry-seconds 600
          docker push registry.digitalocean.com/dowell/flashchords:latest
          doctl registry garbage-collection start

      - name: Create Deployment
        run: doctl apps create-deployment $APP_ID
        env:
          APP_ID: ${{ secrets.DIGITALOCEAN_APP_ID }}
