name: Flash Chords Build
on: [push]
jobs:
  Build-Web-App:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_REGISTRY_KEY }}

      - name: "Build front end"
        run: |
          cd web && npm run build
          cp -a ./build/. ../app/src/main/resources/static/

      - name: "Build back end"
        run: |
          ./gradlew build
          ./gradlew bootBuildImage

      - name: "Tag Image"
        run:
          docker tag dev.dowell/flashchords \
          registry.digitalocean.com/dowell/flashchords:${{github.run_id}}

      - name: "Push to docker registry"
        run: |
          doctl registry login --expiry-seconds 600
          docker push registry.digitalocean.com/dowell/flashchords:${{github.run_id}}
