name: Tests
on: [push]
jobs:
  Test-Frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: cd web && npm install

      - name: "Test front end"
        run: |
          cd web
          npm test

  Test-Backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: "Test back end"
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'app/gradle'
        run: |
          cd app
          ./gradlew test --no-daemon
